# this is jcasc
jenkins:
  clouds:
    - kubernetes:
        name: "kubernetes"
        serverUrl: "https://10.128.0.20:6443"
        skipTlsVerify: true
        credentialsId: "kenkins-token"
        namespace: "jenkins"
        jenkinsUrl: "http://jenkins-master.us-central1-a.c.modern-diode-231316.internal:8085" 
        containerCapStr: 42
        maxRequestsPerHostStr: 64
        retentionTimeout: 5
        connectTimeout: 10
        readTimeout: 20

        templates:
          - name: "k8s-slave"
            namespace: "default"
            label: "linux-x86_64"
            nodeUsageMode: EXCLUSIVE
            containers:
              - name: "jnlp"
                image: "michaeldommet/jenkins-slave:v1"
                alwaysPullImage: true
                workingDir: "/home/jenkins/agent"
                ttyEnabled: true
                resourceRequestCpu: "500m"
                resourceLimitCpu: "1000m"
                resourceRequestMemory: "1Gi"
                resourceLimitMemory: "2Gi"
