# this is jcasc
jenkins:
  clouds:
    - kubernetes:
        name: "kubernetes"
        serverUrl: "https://10.128.0.20:6443"
        skipTlsVerify: true
        credentialsId: "kenkins-token"
        namespace: "jenkins"
        jenkinsUrl: ""http://jenkins-master.us-central1-a.c.modern-diode-231316.internal:8085" 
        containerCapStr: 42
        maxRequestsPerHostStr: 64
        retentionTimeout: 5
        connectTimeout: 10
        readTimeout: 20

        templates:
          - name: "k8s-slave"
            namespace: "default"
            label: "linux-x86_64"
            nodeUsageMode: EXCLUSIVE
            containers:
              - name: "jnlp"
                image: "jenkinsci/jnlp-slave:latest"
                alwaysPullImage: true
                workingDir: "/home/jenkins"
                ttyEnabled: true
                resourceRequestCpu: "500m"
                resourceLimitCpu: "1000m"
                resourceRequestMemory: "1Gi"
                resourceLimitMemory: "2Gi"
            volumes:
              - emptyDirVolume:
                  memory: false
                  mountPath: "/tmp"
            idleMinutes: "1"
            activeDeadlineSeconds: "120"
            slaveConnectTimeout: "1000"
          - name: "my-pod"
            namespace: "jenkins"
            label: "kube-slave"
            nodeUsageMode: EXCLUSIVE
            containers:
              - name: "my-image"
                image: "michaeldommet/jenkins-slave:v1"
                alwaysPullImage: false
                command: /bin/sh -c
                alwaysPullImage: true
                workingDir: "/home/jenkins/agent"
                ttyEnabled: true
                resourceRequestCpu: "500m"
                resourceLimitCpu: "1000m"
                resourceRequestMemory: "1Gi"
                resourceLimitMemory: "2Gi"
            idleMinutes: "1"
            activeDeadlineSeconds: "120"
            slaveConnectTimeout: "1000"
